### ISSUE TITLE
カードを追加するとプログレスバーの色が変わる

### ISSUE THREAD

**Issue by banaoh** [meriy100/rebecca#9]
## 内容
- 現状、タスクを追加するとプログレスバーの色が変化している
## 変更点
- 色の固定

**Comment by meriy100** [comment]
現状 プログレスバーの色はランダムになってます.
デザインを見るためにわざわざ deadline_at と  created_at を調整するのはめんどくさいので.

タスクを追加すると タスクリストを更新するので, その時ランダムに色が変更されます.

なのでプログレスバーの色が何%で変わるかを決めればこの問題は解決します

**Comment by banaoh** [comment]
了解しました。
そしたら、そこの実装はまだ入らないで大丈夫です。
iphoneサイドは
(NowTime - Created_at)/(Deadline_at - Created_at)でvalueを算出し、
val < 0.3 - 赤
0.3 <= val < 0.7 - 黄色
0.7 < val - 青 
以上のように暫定的に色の決め打ちをしています
